"""Add user type and related fields

Revision ID: 54c3347ca87a
Revises: 2025_06_14_add_app_settings_table
Create Date: 2025_06_15 13:28:26.893455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c3347ca87a'
down_revision = '2025_06_14_add_app_settings_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('school_no', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('form', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('initials', sa.String(length=10), nullable=True))

    # Update existing records
    op.execute("UPDATE user SET user_type = 'student' WHERE user_type IS NULL")
    
    # Now make user_type NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('initials')
        batch_op.drop_column('form')
        batch_op.drop_column('batch')
        batch_op.drop_column('school_no')
        batch_op.drop_column('user_type')
    # ### end Alembic commands ###
